# Generated by Django 5.0.4 on 2024-04-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('covoiturage', '0002_delete_trajet_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('heure_depart', models.DateTimeField()),
                ('places_disponibles', models.IntegerField()),
                ('ref_conducteur_trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_trajet_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.trajet')),
                ('ref_client_res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField()),
                ('ref_trajet_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.trajet')),
                ('ref_utilisateur_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_notification', models.DateTimeField()),
                ('ref_utilisateur_notif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='NoteConducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_auteur', to='covoiturage.utilisateur')),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_conducteur', to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueTrajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_trajet', models.DateTimeField()),
                ('frais_partages', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_trajet_HT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.trajet')),
                ('ref_utilisateur_HT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('note', models.IntegerField()),
                ('ref_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_clients', to='covoiturage.utilisateur')),
                ('ref_conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_conducteurs', to='covoiturage.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=255)),
                ('annee', models.IntegerField()),
                ('places_disponibles', models.IntegerField()),
                ('ref_conducteur_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur')),
            ],
        ),
    ]
