# Generated by Django 5.0.4 on 2024-04-29 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='ref_client',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_clients', to='covoiturage.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
