# Generated by Django 5.0.4 on 2024-04-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0004_alter_commentaire_ref_client_alter_utilisateur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='ref_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_clients', to='covoiturage.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
