# Generated by Django 5.0.4 on 2024-04-29 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0005_alter_commentaire_ref_client_alter_utilisateur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='annee',
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='ref_conducteur_vehicule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covoiturage.utilisateur'),
        ),
    ]
