# Generated by Django 5.0.4 on 2024-05-02 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0007_rename_ref_utilisateur_paiement_paiement_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trajet',
            name='ref_conducteur_trajet',
        ),
        migrations.AlterField(
            model_name='paiement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='ref_conducteur',
        ),
        migrations.RemoveField(
            model_name='commentaire',
            name='ref_client',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='ref_utilisateur_notif',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='conducteur_vehicule',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_notification',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='date_paiement',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='paiement',
            old_name='ref_trajet_paiement',
            new_name='trajet',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='trajet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='covoiturage.trajet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trajet',
            name='modele',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='plaque',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NoteConducteur',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.DeleteModel(
            name='Vehicule',
        ),
    ]
