# Generated by Django 5.0.4 on 2024-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0008_remove_trajet_ref_conducteur_trajet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confiirme', 'Confirme'), ('Annule', 'Annule')], default='En attente', max_length=10),
        ),
    ]
