# Generated by Django 5.0.4 on 2024-05-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covoiturage', '0009_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='avance_payee',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
